### ISSUE TITLE
Scroll Bar

### ISSUE THREAD

**Issue by uwzacknelson** [uwblockchain/uwbce#28]
**Describe the bug**
I can't see the scroll bar that should be on right side.

**To Reproduce**
1. Go to the website
2

**Expected behavior**
See the scroll bar 

**Screenshots**
![screen shot 2018-09-06 at 3 04 16 pm](https://user-images.githubusercontent.com/39579141/45187619-2e2b8a80-b1e6-11e8-9146-e6d7dd6bf5dc.png)

**Desktop (please complete the following information):**
 - OS: OS 
 - Browser Safari

**Comment by bpas247** [comment]
Gonna have to investigate this further. Scroll bar is also not showing up on Chrome, but is showing up on Edge.

**Comment by bpas247** [comment]
Looks like commit e25f3abecebefbb121b2290feae2ed6cd81735e0 fixes this issue.

@uwzacknelson Can you confirm when the changes go live? I'd say check back in an hour to see.

**Comment by uwzacknelson** [comment]
Will check in about an hour! Thanks

Zachary Nelson |

President/Co-Founder - UW Blockchain Society

Website: uwblockchain.org

206-354-9520    info@uwblockchain.org

https://www.linkedin.com/in/uwzacharynelson/

**Comment by bpas247** [comment]
@uwzacknelson Looks like the site has been updated and the scrollbar works in chrome for me

**Comment by bpas247** [comment]
Gonna close this issue for now. Re-open it if the scrollbar doesn't appear again.
