### ISSUE TITLE
Update and link favicon

### ISSUE THREAD

**Issue by DugganB** [uwblockchain/uwbce#30]
Update favicon on site to support all browsers and actually show up

**Comment by bpas247** [comment]
What browser(s) are currently not working with the icon? Seems to be working on chrome and edge for me

**Comment by DugganB** [comment]
Safari and other edge cases like mobile require favicons to be generated for them. Should be fixed with PR #31

**Comment by bpas247** [comment]
I'm gonna mark this issue as closed since #31 has been merged.
