### ISSUE TITLE
Updates to integrate with website as soon as possible!

### ISSUE THREAD

**Issue by mark-t-conrad** [uwblockchain/uwbce#37]
** We need to update the information on the website to make strong impressions that turn into sales 
Suggested content updates for the UWBCE website (Mark Cooley): ** 
[Mark Cooley Recommendations.docx](https://github.com/uwblockchain/uwbce/files/2398505/Mark.Cooley.Recommendations.docx)

The design looks great. We should seek to differentiate the expo from all of the other conferences. (there is an obscene amount this fall).
The following are only suggestions and should be discussed by the team and follow any specified approval process for changing the website content.  I am doing a brain dump so you will need to edit the content changes.
The goal is to articulate “why” people should attend in addition to “What” is happening at the expo.
Below the learn more button:
Why you should attend:
Not your everyday blockchain event. Created by students with professional industry mentors, the expositions goals are education and access, not profits. We have designed a day of interactive programming that is a fresh take on the exploration of the blockchain. Don’t miss an opportunity to meet likeminded people, learn new concepts and leave armed with the tools to find your blockchain path. 

** Update for About the Expo **
About the Expo:
The UW Blockchain Society connects students and blockchain industry professionals to provide opportunities for education, innovation, and employment. The UW Blockchain Expo will host expert speakers, and offer two tracks of educational workshops by industry professionals with expertise in a variety of disciplines. They will share their experiences, insights, and the projects they are currently working on. The UW blockchain expo provides unrivaled value for the minimal amount of investment. An opportunity to enjoy a new type of blockchain experience where you not only learn new skills and make connections but leave energized having spent the day with enthusiastic students on one of Americas best university campuses. 
[Add a get tickets button here too]

** Schedule: ** 
Change Introduction to “Event Kick off” then “State of the Blockchain Union”
(I will do 10 minutes to kick off and introduce the team and event than the rest on the general state of the industry today, where it is going, as a lead into the day's topics and speakers.)
On the 3rd on what kind of investment?  To be consistent say “Panel: ….. Investment”  
On the 6th one remove “speaker” and quotes to be consistent 
On the 8th one remove “Big” 
At the end of list put a blurb like “Interested in speaking?” Then the contact us button then “get tickets”

** Workshops: ** 
I would define what we mean by this:
“Workshops are extended interactive sessions with professionals designed to facilitate learning opportunities and skill development.”
Can we give the workshop areas the same love as the speakers with the vertical bar and the tracks n each side? Maybe biz on one and tech on the other? Might be easier to consume.
Can you guys do hover description blurbs? If so we should say who is speaking or participating g a short description. 
GET TICKETS button

**Comment by bpas247** [comment]
#38 resolves this issue.
